apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp-d
  namespace: myreactapp
  labels:
    app: reactapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reactapp
  template:
    metadata:
      labels:
        app: reactapp
    spec:
      containers:
      - name: reactapp
        image: asia-southeast1-docker.pkg.dev/learn-kubernetes-343210/myreactapp/samplereactapp:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: reactapp-svc
  namespace: myreactapp
spec:
  type: NodePort
  selector:
    app: reactapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
